# Generated by Django 6.1 on 2026-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Empty', 'Empty')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('BVoc', 'BVoc'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM')], db_index=True, max_length=10)),
                ('semester', models.CharField(choices=[('Sem 1', 'Sem 1'), ('Sem 2', 'Sem 2'), ('Sem 3', 'Sem 3'), ('Sem 4', 'Sem 4'), ('Sem 5', 'Sem 5'), ('Sem 6', 'Sem 6')], db_index=True, max_length=10)),
                ('is_elective', models.BooleanField(default=False)),
            ],
        ),
    ]
