# Generated by Django 6.1 on 2026-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('BVoc', 'BVoc'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM'), ('BBA(FS)', 'BBA (Financial Studies)')], db_index=True, max_length=10),
        ),
    ]
