# Generated by Django 6.1 on 2026-08-29 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_created_at_alter_attendance_marked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_slot',
            field=models.CharField(default='Regular', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_batch', 'student', 'date', 'time_slot')},
        ),
    ]
