# Generated by Django 6.1 on 2026-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbatch',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
    ]
