# Generated by Django 6.1 on 2026-08-29 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('class_batch', 'student', 'date', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_batch')},
        ),
    ]
