# Generated by Django 6.1 on 2026-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbatch',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
