# Generated by Django 6.1 on 2026-08-29 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_classbatch_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceticket',
            unique_together={('attendance', 'student')},
        ),
    ]
