# Generated by Django 5.2.4 on 2026-09-19 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_timetableactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_batch', 'date'], name='attendance__class_b_a0f705_idx'),
        ),
    ]
