# Generated by Django 5.2.4 on 2026-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_notification_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringduty',
            name='total_students_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringduty',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Empty', 'Empty')], default='Pending', max_length=10),
        ),
    ]
