# Generated by Django 6.1.1 on 2026-09-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendance_id_alter_attendanceticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringduty',
            name='class_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.classbatch'),
        ),
    ]
