# Generated by Django 6.1.1 on 2026-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_monitoringduty_class_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.CharField(default='2026-2027', max_length=20)),
            ],
        ),
    ]
