# Generated by Django 6.1.1 on 2026-09-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_timetable_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
