# Generated by Django 6.1 on 2026-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_timetable_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
