# Generated by Django 6.1.1 on 2026-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_auditlog_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
