# Generated by Django 5.2.4 on 2026-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_recovery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Finance', 'Finance')], max_length=255),
        ),
    ]
